import fs from 'fs/promises';
import type { Report } from '@workflow-archaeologist/core';

function confidenceBadge(confidence: string): string {
  const map: Record<string, string> = {
    high: '🟢 high',
    medium: '🟡 medium',
    low: '🔴 low',
  };
  return map[confidence] ?? confidence;
}

function riskIcon(type: string): string {
  const map: Record<string, string> = {
    UNPINNED_ACTION: '📌',
    HARDCODED_SECRET: '🔑',
    MISSING_CACHE: '⚡',
    SUSPICIOUS_TIMEOUT: '⏱️',
    INVALID_YAML: '❌',
  };
  return map[type] ?? '⚠️';
}

export async function generateMarkdown(
  report: Report,
  outputPath: string
): Promise<void> {
  const lines: string[] = [];

  lines.push('# Workflow Archaeologist Report');
  lines.push('');
  lines.push(`**Repository:** \`${report.repoPath}\``);
  lines.push(`**Generated:** ${report.generatedAt}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Commits analysed | ${report.totalCommitsAnalysed} |`);
  lines.push(`| Decisions explained | ${report.decisions.length} |`);
  lines.push(`| Risk flags | ${report.risks.length} |`);
  lines.push(`| Quick wins | ${report.quickWins.length} |`);
  lines.push('');

  // quick wins
  if (report.quickWins.length > 0) {
    lines.push('## ⚡ Quick Wins');
    lines.push('');
    for (const win of report.quickWins) {
      const sha = win.commitSha ? ` \`${win.commitSha.slice(0, 8)}\`` : '';
      lines.push(`- **[${win.type}]** ${win.description}`);
      lines.push(`  \`${win.filePath}\`${sha}`);
    }
    lines.push('');
  }

  // decisions
  lines.push('## 🔍 Decision Registry');
  lines.push('');
  if (report.decisions.length === 0) {
    lines.push('_No decisions analysed._');
  } else {
    for (const d of report.decisions) {
      const sha = d.commitSha.slice(0, 8);
      const badge = d.isPlaceholder ? '⬜ placeholder' : confidenceBadge(d.confidence);
      lines.push(`### \`${sha}\` — ${d.filePath}`);
      lines.push('');
      lines.push(`**Confidence:** ${badge}`);
      lines.push('');
      lines.push(d.reason);
      if (d.recommendation) {
        lines.push('');
        lines.push(`> **Recommendation:** ${d.recommendation}`);
      }
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  // risks
  lines.push('## ⚠️ Risk Flags');
  lines.push('');
  if (report.risks.length === 0) {
    lines.push('_No risks detected._');
  } else {
    for (const r of report.risks) {
      const icon = riskIcon(r.type);
      const line = r.line ? ` (line ${r.line})` : '';
      lines.push(`- ${icon} **${r.type}** — ${r.description}`);
      lines.push(`  \`${r.filePath}\`${line}`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('_Generated by [Workflow Archaeologist](https://github.com/your-org/workflow-archaeologist)_');

  await fs.writeFile(outputPath, lines.join('\n'), 'utf-8');
}